name: Adding Job B
on:
  workflow_run:
    workflows: ["Add Job"]
    types:
      - completed
jobs:
  consume:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: shared-data
          path: shared-data-directory

      - name: Read shared data
        run: cat shared-data-directory/shared-data.txt
